# -*- coding: utf-8 -*-
"""Analisededados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uiF79v6Xad5LK3qXZz3HlmGAGvOSBG1V
"""

import pandas as pd
import plotly.express as px
import streamlit as st

#LENDO A BASE DE DADOS RELACIONADOS A COVID-19 NO BRASIL (INFORMACOES OFICIAIS DO MINISTERIO DA SAUDE)
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')

#ALTERANDO OS NOMES DAS COLUNAS DA TABELA
df = df.rename(columns={'newDeaths': 'NOVOS ÓBITOS','newCases': 'NOVOS CASOS','deaths_per_100k_inhabitants': 'ÓBITOS POR 100 MIL HABITANTES','totalCases_per_100k_inhabitants':'CASOS POR 100 MIL HABITANTES'})

#SELECÃO DOS ESTADOS
estados = list(df['state'].unique())
state = st.sidebar.selectbox('ESCOLHA O ESTADO', estados)

#SELEÇÃO DA COLUNA
colunas = ['NOVOS ÓBITOS','NOVOS CASOS','ÓBITOS POR 100 MIL HABITANTES','CASOS POR 100 MIL HABITANTES']
column = st.sidebar.selectbox('ESCOLHA UMA OPÇÃO', colunas)

#SELEÇÃO DAS LINHAS QUE PERTECEM A CADA ESTADO SELECIONADO
df = df[df['state'] == state]

fig = px.line(df, x="date", y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('DADOS COVID-19 NO BRASIL - PUC MINAS')
st.write('Escolha o estado e o tipo de informação para ser mostrada no gráfico atráves do menu lateral.')

st.plotly_chart(fig, use_container_widht=True)

st.caption('Pontifícia Universidade Católica de Minas Gerais - Danilo B Mateus')
